import { type Config } from "tailwindcss";

const colorKeys = [
  "gray",
  "stone",
  "red",
  "pink",
  "purple",
  "violet",
  "indigo",
  "blue",
  "cyan",
  "teal",
  "green",
  "lime",
  "yellow",
  "orange",
  "brown",
  "sand",
  "camo",
];

const colors: Record<string, string> = {};
for (const key of colorKeys) {
  for (let index = 0; index < 13; index++) {
    colors[`${key}-${index}`] = `var(--${key}-${index})`;
  }
}

const themeKeys = [
  "surface-1",
  "surface-2",
  "surface-3",
  "surface-4",
  "text-1",
  "text-2",
  "brand",
  "link",
  "link-visited",
  "ui-1",
  "ui-2",
  "ui-3",
  "ui-4",
];

for (const key of themeKeys) {
  colors[key] = `var(--${key})`;
}

export default {
  content: [
    "{routes,islands,components}/**/*.{ts,tsx}",
  ],
  theme: {
    animation: {
      "fade-in": "var(--animation-fade-in)",
      "fade-in-bloom": "var(--animation-fade-in-bloom)",
      "fade-out": "var(--animation-fade-out)",
      "fade-out-bloom": "var(--animation-fade-out-bloom)",
      "scale-up": "var(--animation-scale-up)",
      "scale-down": "var(--animation-scale-down)",
      "slide-out-up": "var(--animation-slide-out-up)",
      "slide-out-down": "var(--animation-slide-out-down)",
      "slide-out-right": "var(--animation-slide-out-right)",
      "slide-out-left": "var(--animation-slide-out-left)",
      "slide-in-up": "var(--animation-slide-in-up)",
      "slide-in-down": "var(--animation-slide-in-down)",
      "slide-in-right": "var(--animation-slide-in-right)",
      "slide-in-left": "var(--animation-slide-in-left)",
      "shake-x": "var(--animation-shake-x)",
      "shake-y": "var(--animation-shake-y)",
      "spin": "var(--animation-spin)",
      "ping": "var(--animation-ping)",
      "blink": "var(--animation-blink)",
      "float": "var(--animation-float)",
      "bounce": "var(--animation-bounce)",
      "pulse": "var(--animation-pulse)",
    },
    aspectRatio: {
      "square": "var(--ratio-square)",
      "landscape": "var(--ratio-landscape)",
      "portrait": "var(--ratio-portrait)",
      "widescreen": "var(--ratio-widescreen)",
      "ultrawide": "var(--ratio-ultrawide)",
      "golden": "var(--ratio-golden)",
    },
    borderRadius: {
      "1": "var(--radius-1)",
      "2": "var(--radius-2)",
      "3": "var(--radius-3)",
      "4": "var(--radius-4)",
      "5": "var(--radius-5)",
      "6": "var(--radius-6)",

      "drawn-1": "var(--radius-drawn-1)",
      "drawn-2": "var(--radius-drawn-2)",
      "drawn-3": "var(--radius-drawn-3)",
      "drawn-4": "var(--radius-drawn-4)",
      "drawn-5": "var(--radius-drawn-5)",
      "drawn-6": "var(--radius-drawn-6)",

      "round": "var(--radius-round)",
      "blob-1": "var(--radius-blob-1)",
      "blob-2": "var(--radius-blob-2)",
      "blob-3": "var(--radius-blob-3)",
      "blob-4": "var(--radius-blob-4)",
      "blob-5": "var(--radius-blob-5)",

      "cond-1": "var(--radius-conditional-1)",
      "cond-2": "var(--radius-conditional-2)",
      "cond-3": "var(--radius-conditional-3)",
      "cond-4": "var(--radius-conditional-4)",
      "cond-5": "var(--radius-conditional-5)",
      "cond-6": "var(--radius-conditional-6)",
    },
    borderWidth: {
      "1": "var(--border-size-1)",
      "2": "var(--border-size-2)",
      "3": "var(--border-size-3)",
      "4": "var(--border-size-4)",
      "5": "var(--border-size-5)",
    },
    boxShadow: {
      "1": "var(--shadow-1)",
      "2": "var(--shadow-2)",
      "3": "var(--shadow-3)",
      "4": "var(--shadow-4)",
      "5": "var(--shadow-5)",
      "6": "var(--shadow-6)",

      "in-0": "var(--inner-shadow-0)",
      "in-1": "var(--inner-shadow-1)",
      "in-2": "var(--inner-shadow-2)",
      "in-3": "var(--inner-shadow-3)",
      "in-4": "var(--inner-shadow-4)",
    },
    colors,
    fontFamily: {
      "sans": "var(--font-sans)",
      "serif": "var(--font-serif)",
      "mono": "var(--font-mono)",
    },
    fontSize: {
      "00": "var(--font-size-00)",
      "0": "var(--font-size-0)",
      "1": "var(--font-size-1)",
      "2": "var(--font-size-2)",
      "3": "var(--font-size-3)",
      "4": "var(--font-size-4)",
      "5": "var(--font-size-5)",
      "6": "var(--font-size-6)",
      "7": "var(--font-size-7)",
      "8": "var(--font-size-8)",
      "fl-0": "var(--font-size-fluid-0)",
      "fl-1": "var(--font-size-fluid-1)",
      "fl-2": "var(--font-size-fluid-2)",
      "fl-3": "var(--font-size-fluid-3)",
    },
    fontWeight: {
      "1": "var(--font-weight-1)",
      "2": "var(--font-weight-2)",
      "3": "var(--font-weight-3)",
      "4": "var(--font-weight-4)",
      "5": "var(--font-weight-5)",
      "6": "var(--font-weight-6)",
      "7": "var(--font-weight-7)",
      "8": "var(--font-weight-8)",
      "9": "var(--font-weight-9)",
    },
    letterSpacing: {
      "0": "var(--font-letterspacing-0)",
      "1": "var(--font-letterspacing-1)",
      "2": "var(--font-letterspacing-2)",
      "3": "var(--font-letterspacing-3)",
      "4": "var(--font-letterspacing-4)",
      "5": "var(--font-letterspacing-5)",
      "6": "var(--font-letterspacing-6)",
      "7": "var(--font-letterspacing-7)",
    },
    lineHeight: {
      "00": "var(--font-lineheight-00)",
      "0": "var(--font-lineheight-0)",
      "1": "var(--font-lineheight-1)",
      "2": "var(--font-lineheight-2)",
      "3": "var(--font-lineheight-3)",
      "4": "var(--font-lineheight-4)",
      "5": "var(--font-lineheight-5)",
    },
    spacing: {
      "000": "var(--size-000)",
      "00": "var(--size-00)",
      "0": "var(--size-0)",
      "1": "var(--size-1)",
      "2": "var(--size-2)",
      "3": "var(--size-3)",
      "4": "var(--size-4)",
      "5": "var(--size-5)",
      "6": "var(--size-6)",
      "7": "var(--size-7)",
      "8": "var(--size-8)",
      "9": "var(--size-9)",
      "10": "var(--size-10)",
      "11": "var(--size-11)",
      "12": "var(--size-12)",
      "13": "var(--size-13)",
      "14": "var(--size-14)",
      "15": "var(--size-15)",

      "fl-1": "var(--size-fluid-1)",
      "fl-2": "var(--size-fluid-2)",
      "fl-3": "var(--size-fluid-3)",
      "fl-4": "var(--size-fluid-4)",
      "fl-5": "var(--size-fluid-5)",
      "fl-6": "var(--size-fluid-6)",
      "fl-7": "var(--size-fluid-7)",
      "fl-8": "var(--size-fluid-8)",
      "fl-9": "var(--size-fluid-9)",
      "fl-10": "var(--size-fluid-10)",
    },
    width: {
      "full": "100%",

      "000": "var(--size-000)",
      "00": "var(--size-00)",
      "0": "var(--size-0)",
      "1": "var(--size-1)",
      "2": "var(--size-2)",
      "3": "var(--size-3)",
      "4": "var(--size-4)",
      "5": "var(--size-5)",
      "6": "var(--size-6)",
      "7": "var(--size-7)",
      "8": "var(--size-8)",
      "9": "var(--size-9)",
      "10": "var(--size-10)",
      "11": "var(--size-11)",
      "12": "var(--size-12)",
      "13": "var(--size-13)",
      "14": "var(--size-14)",
      "15": "var(--size-15)",

      "fl-1": "var(--size-fluid-1)",
      "fl-2": "var(--size-fluid-2)",
      "fl-3": "var(--size-fluid-3)",
      "fl-4": "var(--size-fluid-4)",
      "fl-5": "var(--size-fluid-5)",
      "fl-6": "var(--size-fluid-6)",
      "fl-7": "var(--size-fluid-7)",
      "fl-8": "var(--size-fluid-8)",
      "fl-9": "var(--size-fluid-9)",
      "fl-10": "var(--size-fluid-10)",

      "content-1": "var(--size-content-1)",
      "content-2": "var(--size-content-2)",
      "content-3": "var(--size-content-3)",

      "header-1": "var(--size-header-1)",
      "header-2": "var(--size-header-2)",
      "header-3": "var(--size-header-3)",

      "xxs": "var(--size-xxs)",
      "xs": "var(--size-xs)",
      "sm": "var(--size-sm)",
      "md": "var(--size-md)",
      "lg": "var(--size-lg)",
      "xl": "var(--size-xl)",
      "xxl": "var(--size-xxl)",
    },
    zIndex: {
      "1": "var(--layer-1)",
      "2": "var(--layer-2)",
      "3": "var(--layer-3)",
      "4": "var(--layer-4)",
      "5": "var(--layer-5)",
      "important": "var(--layer-important)",
    },
  },
} satisfies Config;
